### ISSUE TITLE
Export pathways with names containing special char like "/"

### ISSUE THREAD

**Issue by kevintc** [pennatula/PathVisioRPC#4]
Hello,

I'm trying to use the export to svg method using python and PathVisioRPC server.
It works great but I have an issue with some pathways.

The software takes the name of the pathway (in the first line of the gpml file) in order to build the export name, but it fails to export for names like "EGF/EGFR Signaling Pathway" : http://www.wikipathways.org/index.php/Pathway:WP437
The "/" in the name ruins it :'(

Is there a way to manually specify the output name ? (I can define the output folder but not the output file)...
Or maybe fix this issue by replacing "/" character in the output ?

Thanks a lot :)
Best regards

**Comment by pennatula** [comment]
Sorry, just saw the issue today. I will try to get this work asap if you still need it.

**Comment by kevintc** [comment]
Hey, thank you for the follow up ! Would be great if you can fix this ! thanks :)

**Comment by pennatula** [comment]
Functions added 

exportPathwayByFile(pathwayfilepath, exportfiletype, resultdirectory, exportfilename)

exportPathwayFromURIByFile(uri, exportfiletype, resultdirectory,exportfilename)

**Comment by pennatula** [comment]
Use v1.2.0. Let me know if it doesn't work :+1:
