### ISSUE TITLE
build.xml uses plugin-common.jar but doesn't define embed.jars

### ISSUE THREAD

**Issue by egonw** [pennatula/PathVisioRPC#5]
Anwesha, some weeks (probably Feb/Mar or so) I promised Tina to get our Jenkins more plugins compiling, and I just started with the PathVisioRPC plugin:

https://jenkins.bigcat.unimaas.nl/job/PathVisio%20-%20PathVisioRPC/4/console

This is just a note that your build.xml uses the plugin-common.xml, but the one from PathVisio master expects that a Ant parameter "embed.jars" is defined, that your build.xml does not seem to define:

/var/lib/jenkins/jobs/PathVisio (common bundles)/workspace/plugin-common.xml:57: Reference embed.jars not found.

Consider this a wishlist item; it's not critical, and I may try to find some time myself. That said, the fix should be trivial, I guess, so if you have a quick fix, that would be great.

**Comment by egonw** [comment]
Anwesha, I think this patch will do it...

**Comment by pennatula** [comment]
Thanks for the patch!
